# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ribs-tutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'RIBs', :git => 'https://github.com/uber/RIBs', :commit => 'ffc489f00db785c8c0051678393f7aba0d52f1a4'

end
